<?php 
require_once "layouts/config.php";

        // $sql11 = "SELECT MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME,MILJON_EMPLOYEE.MEMPLOYEE_ID,  concat(MILJON_EMPLOYEE.LST_NAME, ' ' , MILJON_EMPLOYEE.FST_NAME) as FULL_NAME  from MILJON_EMPLOYEE_DESIGNATION_MASTER
        //     INNER JOIN MILJON_EMPLOYEE
        //     ON MILJON_EMPLOYEE_DESIGNATION_MASTER.MEDM_ID = MILJON_EMPLOYEE.H_ID
        //     WHERE (MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME = 'ZBM' OR MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME = 'ZH' )
        //     GROUP BY MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME,MILJON_EMPLOYEE.MEMPLOYEE_ID";
        // $ZBM_array = mysqli_query($link, $sql11);

        //WHERE (MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME = 'ZBM' OR MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME = 'ZH' ) and (find_in_set(MILJON_EMPLOYEE.MEMPLOYEE_ID, GET_MILJON_EMPLOYEE_TEAM_MEMBER_DETAIL_HIERARCHY(<script>document.getElementById('AllZBM').value</sript>)))

            $sql12 = "SELECT MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME, MILJON_EMPLOYEE.MEMPLOYEE_ID, concat(MILJON_EMPLOYEE.LST_NAME, ' ' , MILJON_EMPLOYEE.FST_NAME) as FULL_NAME  from MILJON_EMPLOYEE_DESIGNATION_MASTER
                INNER JOIN MILJON_EMPLOYEE
                ON MILJON_EMPLOYEE_DESIGNATION_MASTER.MEDM_ID = MILJON_EMPLOYEE.H_ID
                WHERE MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME = 'RBM' 
                GROUP BY MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME,MILJON_EMPLOYEE.MEMPLOYEE_ID";
        $RBM_array = mysqli_query($link, $sql12);

        $sql13 = "SELECT MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME, MILJON_EMPLOYEE.MEMPLOYEE_ID, concat(MILJON_EMPLOYEE.LST_NAME, ' ' , MILJON_EMPLOYEE.FST_NAME) as FULL_NAME  from MILJON_EMPLOYEE_DESIGNATION_MASTER
            INNER JOIN MILJON_EMPLOYEE
            ON MILJON_EMPLOYEE_DESIGNATION_MASTER.MEDM_ID = MILJON_EMPLOYEE.H_ID
            WHERE MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME = 'ABM'
            GROUP BY MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME,MILJON_EMPLOYEE.MEMPLOYEE_ID";
        $ABM_array = mysqli_query($link, $sql13);

        $sql14 = "SELECT MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME,MILJON_EMPLOYEE.MEMPLOYEE_ID, concat(MILJON_EMPLOYEE.LST_NAME, ' ' , MILJON_EMPLOYEE.FST_NAME) as FULL_NAME  from MILJON_EMPLOYEE_DESIGNATION_MASTER
            INNER JOIN MILJON_EMPLOYEE
            ON MILJON_EMPLOYEE_DESIGNATION_MASTER.MEDM_ID = MILJON_EMPLOYEE.H_ID
            WHERE MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME = 'KAM' OR MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME = 'SR KAM'
            GROUP BY MILJON_EMPLOYEE_DESIGNATION_MASTER.NAME,MILJON_EMPLOYEE.MEMPLOYEE_ID";
        $KAM_array = mysqli_query($link, $sql14);


        // echo $_POST['data'];
?>


